// Preset schema_fields bundle for the Portuguese market — offered as a one-click
// "Adicionar Campos PT" action on the admin Schema Fields page (POST /api/schema with
// this array in the body).
export const PT_PATIENT_FIELDS = [
  {
    fieldName: 'sex',
    label: 'Sexo',
    fieldType: 'enum',
    enumValues: ['Masculino', 'Feminino', 'Outro'],
    required: false,
    rollout: 100,
  },
  {
    fieldName: 'id_type',
    label: 'Documento',
    description: 'Cartão de Cidadão / Passaporte',
    fieldType: 'enum',
    enumValues: ['Cartão de Cidadão', 'Passaporte', 'Outro'],
    required: false,
    rollout: 100,
  },
  { fieldName: 'id_number', label: 'Nº de Identificação', fieldType: 'string', required: false, rollout: 100 },
  { fieldName: 'nif', label: 'NIF', fieldType: 'string', required: false, rollout: 100 },
  { fieldName: 'sns_number', label: 'Nº Utente SNS', fieldType: 'string', required: false, rollout: 100 },
  { fieldName: 'address', label: 'Morada', fieldType: 'string', required: false, rollout: 100 },
  { fieldName: 'postal_code', label: 'Código Postal', fieldType: 'string', required: false, rollout: 100 },
  { fieldName: 'city', label: 'Cidade', fieldType: 'string', required: false, rollout: 100 },
  {
    fieldName: 'emergency_contact_name',
    label: 'Contacto de Emergência (Nome)',
    fieldType: 'string',
    required: false,
    rollout: 100,
  },
  {
    fieldName: 'emergency_contact_phone',
    label: 'Contacto de Emergência (Telefone)',
    fieldType: 'string',
    required: false,
    rollout: 100,
  },
  { fieldName: 'consent_rgpd', label: 'Consentimento RGPD', fieldType: 'boolean', required: false, rollout: 100 },
  {
    fieldName: 'consent_treatment',
    label: 'Consentimento Tratamento',
    fieldType: 'boolean',
    required: false,
    rollout: 100,
  },
  {
    fieldName: 'consent_imaging',
    label: 'Consentimento Imagens/RX',
    fieldType: 'boolean',
    required: false,
    rollout: 100,
  },
  {
    fieldName: 'consent_contact',
    label: 'Consentimento SMS/Email',
    fieldType: 'boolean',
    required: false,
    rollout: 100,
  },
  { fieldName: 'medical_allergies', label: 'Alergias', fieldType: 'string', required: false, rollout: 100 },
  { fieldName: 'medical_medications', label: 'Medicação', fieldType: 'string', required: false, rollout: 100 },
  { fieldName: 'medical_pregnant', label: 'Gravidez', fieldType: 'boolean', required: false, rollout: 100 },
  { fieldName: 'medical_heart', label: 'Problemas Cardíacos', fieldType: 'boolean', required: false, rollout: 100 },
  { fieldName: 'medical_diabetes', label: 'Diabetes', fieldType: 'boolean', required: false, rollout: 100 },
  { fieldName: 'medical_hypertension', label: 'Hipertensão', fieldType: 'boolean', required: false, rollout: 100 },
  {
    fieldName: 'medical_infectious',
    label: 'Doenças Infeciosas Relevantes',
    fieldType: 'string',
    required: false,
    rollout: 100,
  },
  { fieldName: 'medical_surgeries', label: 'Cirurgias Anteriores', fieldType: 'string', required: false, rollout: 100 },
  {
    fieldName: 'alcohol_use',
    label: 'Álcool',
    fieldType: 'enum',
    enumValues: ['Nunca', 'Ocasionalmente', 'Frequentemente'],
    required: false,
    rollout: 100,
  },
  { fieldName: 'reason_for_visit', label: 'Motivo da Consulta', fieldType: 'string', required: false, rollout: 100 },
  { fieldName: 'symptoms', label: 'Dores/Sintomas', fieldType: 'string', required: false, rollout: 100 },
  {
    fieldName: 'dental_anxiety',
    label: 'Ansiedade Dentária (0-10)',
    fieldType: 'integer',
    required: false,
    rollout: 100,
  },
  {
    fieldName: 'oral_hygiene_frequency',
    label: 'Higiene Oral',
    fieldType: 'enum',
    enumValues: ['1x/dia', '2x/dia', '3x/dia', 'Irregular'],
    required: false,
    rollout: 100,
  },
];
